source "https://rubygems.org"

gem "dry-struct"        # Modelos de datos tipados
gem "dry-types"         # Sistema de tipos para dry-struct
gem "rufus-scheduler"   # Cron-like polling
gem "dotenv"            # Carga de .env
